version: '3.4'
services:

    timescale:
        image: timescale/timescaledb
        ports:
            - "5432:5432"
        expose:
            - "5432"
        networks:
            - cryptobox
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
        volumes:
            - ./timescale_data:/var/lib/postgresql/data

    # t2_worker:
    #     build: ./kryptobot/workers
    #     command: bash -c "pip install -e . && celery -A kryptobot.workers.t2 worker -l info"
    #     working_dir: /usr/src/app
    #     volumes:
    #         - ./:/usr/src/app
    #     networks:
    #         - cryptobox

    # harvester_worker:
    #     build: ./kryptobot/workers
    #     command: bash -c "pip install -e . && celery -A kryptobot.workers.harvester worker -l info"
    #     working_dir: /usr/src/app
    #     volumes:
    #         - ./:/usr/src/app
    #     networks:
    #         - cryptobox

    # redbeat:
    #     build: ./kryptobot/workers
    #     command: bash -c "pip install -e . && celery -A kryptobot.workers beat -S redbeat.RedBeatScheduler"
    #     working_dir: /usr/src/app
    #     volumes:
    #         # - app:/usr/src/app
    #         - ./:/usr/src/app
    #     networks:
    #         - cryptobox

    # all_workers:
    #     build: ./kryptobot/workers
    #     command: bash -c "pip install -e . && celery -A kryptobot.workers worker -l info"
    #     # Can't get Procfile to work
    #     # command: honcho start
    #     working_dir: /usr/src/app
    #     volumes:
    #         # - app:/usr/src/app
    #         - ./:/usr/src/app
    #     networks:
    #         - cryptobox

    # flower:
    #     build: ./kryptobot/workers
    #     command: bash -c "pip install -e . && celery -A kryptobot.workers flower --broker=redis://redis:6379/0"
    #     working_dir: /usr/src/app
    #     ports:
    #         - "5555:5555"
    #     expose:
    #         - "5555"
    #     volumes:
    #         - ./:/usr/src/app
    #     networks:
    #         - cryptobox

    # rest_api:
    #     build: ./kryptobot/server
    #     command: "python ./server/run.py"
    #     working_dir: /usr/src/app
    #     ports:
    #         - "5000:5000"
    #     expose:
    #         - "5000"
    #     volumes:
    #         - ./kryptobot:/usr/src/app
    #     networks:
    #         - cryptobox

    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            # - REDIS_PASSWORD=password123
        ports:
            - '6379:6379'
        networks:
            - cryptobox

    jupyter:
        build: .
        command: jupyter lab --ip=0.0.0.0 --allow-root
        ports:
            - "8888:8888"
            - "5000:5000"
            - "5555:5555"
        working_dir: /usr/src/app/notebooks
        expose:
            - "8888"
            - "5000"
            # - "5555"
        volumes:
            - ./:/usr/src/app
            - ./.catalyst:/root/.catalyst
            - ./.catalyst_pickles:/root/.catalyst_pickles
        networks:
            - cryptobox

networks:
    cryptobox:
        driver: bridge
