version: '3.4'
services:

    # timescale:
    #     image: timescale/timescaledb
    #     ports:
    #         - "5432:5432"
    #     expose:
    #         - "5432"
    #     networks:
    #         - cryptobox
    #     environment:
    #         - POSTGRES_PASSWORD=password
    #         - POSTGRES_USER=postgres

    redis:
        image: 'bitnami/redis:latest'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            # - REDIS_PASSWORD=password123
        ports:
            - '6379:6379'
        networks:
            - cryptobox

    jupyter:
        build: .
        command: jupyter lab --ip=0.0.0.0 --allow-root
        ports:
            - "8888:8888"
        working_dir: /usr/src/app/notebooks
        expose:
            - "8888"
        volumes:
            - ./:/usr/src/app
        networks:
            - cryptobox

networks:
    cryptobox:
        driver: bridge
